version: '3.7'
 
services:
 
  postgre-sql:
    image: postgres:latest
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=dockerUser
      - POSTGRES_PASSWORD=dockerPostgresPassword
      - POSTGRES_DB=actorsDb
    ports:
      - "127.0.0.1:6542:5432"

  api:
    build: .
    environment: 
        DBServer: "postgre-sql"
        ASPNETCORE_ENVIRONMENT: "Development"
    ports: 
        - "127.0.0.1:8081:80"
    restart: always